### PR TITLE
update readme,fix num

### PR DESCRIPTION
**Pull request by shepf**
update readme,fix num

### CODE REVIEW

**Comment by weijiekoh** [comment]
Thanks @shepf !

FYI, this repository is no longer maintained, and a lot of the code is obsolete. It uses very old versions of snarkjs and circom.

**Comment by shepf** [comment]
Why not maintain it?  it's a cool project!

**Comment by weijiekoh** [comment]
I think it needs to be rewritten :) I wrote it as a starter project to learn how to work on zksnarks and I'm currently busy with other projects.

**Comment by shepf** [comment]
> I think it needs to be rewritten :) I wrote it as a starter project to learn how to work on zksnarks and I'm currently busy with other projects.

ok, looking forward to your future improvement. this is a very cool project!

**Pull request merged**
